const SIGNER_ONLY_ENVIRONMENT_KEYS = [
  'CHAINWHISPER_SIGNER_PRIVATE_KEY',
  'CHAINWHISPER_SIGNER_AES_KEY',
  'CHAINWHISPER_SIGNER_VAULT_PASSPHRASE',
  'CHAINWHISPER_SIGNER_ENV_FILE',
  'CHAINWHISPER_SIGNER_CONFIG_FILE',
  'CHAINWHISPER_SIGNER_EXPECTED_WALLET',
  'CHAINWHISPER_SIGNER_STATE_DIRECTORY',
  'CHAINWHISPER_SIGNER_CONFIRMATION_CHANNEL',
  'CHAINWHISPER_SIGNER_CONFIRMATION_TIMEOUT_MS',
  'CHAINWHISPER_SIGNER_EXPIRY_SKEW_MS',
] as const;

export const removeSignerOnlyEnvironment = (
  environment: Record<string, string | undefined>,
): void => {
  for (const key of SIGNER_ONLY_ENVIRONMENT_KEYS) {
    delete environment[key];
  }
};
